### ISSUE TITLE
Installation is impossible

### ISSUE THREAD

**Issue by TheSystemGuy1337** [qeesung/asciiplayer#16]
Really fun, this software has been rendered completely obsolete as you can't even install it. Any attempt to install it tosses 
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

Please port to C++ and add to the apt repository. Thank you.

**Comment by FirstAfterGod2501** [comment]
run this:
`go mod init  example.com/m`
`go mod tidy`
`go mod vendor`
`go build`

**Comment by TheSystemGuy1337** [comment]
> run this: `go mod init example.com/m` `go mod tidy` `go mod vendor` `go build`

This issue is far too old, and I have moved on. You have effectively wasted your own time replying to a dead issue. I'm sorry, man.
